test: &default
  client_id: AeugXhBMCzEeqJleP05WLIqQ51vujS-thtPYoL4xuRal9_B3-olcbKxrs-9n
  client_secret: EETkXxDWu6Vb9RZpRKH6v2UcUN0_d8fH15THWnR-1q2nd8C9ezl6cYu9S6A1
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: desktop.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
